# Generated by Django 4.1.7 on 2023-10-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_booking_user_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='00:00:00', max_length=254),
        ),
    ]
