# Generated by Django 4.1.7 on 2023-11-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0006_rename_time_booking_end_time_booking_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
